# Generated by Django 5.0.6 on 2026-06-18 13:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='建筑面积'),
        ),
        migrations.CreateModel(
            name='PrepaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='账户余额')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_account', to='communities.room')),
            ],
            options={
                'verbose_name': '预存款账户',
                'verbose_name_plural': '预存款账户',
            },
        ),
        migrations.CreateModel(
            name='PrepaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_no', models.CharField(max_length=40, unique=True, verbose_name='流水号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易后余额')),
                ('txn_type', models.CharField(choices=[('recharge', '充值'), ('deduct', '抵扣')], max_length=20, verbose_name='交易类型')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='communities.prepaidaccount')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_transactions', to='communities.bill')),
            ],
            options={
                'verbose_name': '预存款流水',
                'verbose_name_plural': '预存款流水',
                'ordering': ['-created_at'],
            },
        ),
    ]
