# Generated by Django 5.0.6 on 2026-06-18 13:58

from decimal import Decimal
from django.db import migrations, models


def set_actual_paid(apps, schema_editor):
    Payment = apps.get_model("communities", "Payment")
    Payment.objects.update(actual_paid=models.F("amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_room_area_prepaidaccount_prepaidtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='actual_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实付金额'),
        ),
        migrations.AddField(
            model_name='payment',
            name='prepaid_deduct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='预存款抵扣'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应收金额'),
        ),
        migrations.RunPython(set_actual_paid),
    ]
